### ISSUE TITLE
error after building

### ISSUE THREAD

**Issue by ArthurHDRodrigues** [indiv0/colonize#99]
I ran 
```
git clone https://github.com/indiv0/colonize
cd colonize
```

and then

`cargo run --release`

Like the main page said, then the following errors appears:

```
error[E0658]: use of unstable library feature 'clamp'
   --> crates/core/src/terrain.rs:106:28
    |
106 |             let distance = i32::clamp(point.y() - height, i8::MIN as i32, i8::MAX as i32) as i8;
    |                            ^^^^^^^^^^
    |
    = note: see issue #44095 <https://github.com/rust-lang/rust/issues/44095> for more information

error[E0658]: use of unstable library feature 'clamp'
   --> crates/core/src/terrain.rs:202:28
    |
202 |             let distance = i32::clamp((point.y() as f64 - height) as i32, i8::MIN as i32, i8::MAX as i32) as i8;
    |                            ^^^^^^^^^^
    |
    = note: see issue #44095 <https://github.com/rust-lang/rust/issues/44095> for more information

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `colonize_core`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Feel free to ask for additional info, if needed :)
-Arthur

**Comment by indiv0** [comment]
Could you try building on nightly Rust?

That is:
```shell
rustup default nightly
rustup update
cargo clean
cargo build --release
```

**Comment by ArthurHDRodrigues** [comment]
Thank you for the reply!

It compiled fine on nightly Rust, I didn't consider this because I'm kind of a noob with Rust...

Now I have another problem, it panicked when I ran  `./target/release/colonize`. This is the right binary to run, right?

The full output can be seen below:
```
thread 'thread 'IO Task Pool (0)IO Task Pool (1)' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: PathLoaderError(NotFound("/home/username/coding/colonize/target/release/assets/shaders/forward.vert"))called `Result::unwrap()` on an `Err` value: PathLoaderError(NotFound("/home/username/coding/colonize/target/release/assets/shaders/forward.frag"))', ', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.4.0/src/asset_server.rs/home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.4.0/src/asset_server.rs::298298::6060

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.4.0/src/pipeline/pipeline_compiler.rs:80:49
thread 'main' panicked at 'Task thread panicked while executing.: Any { .. }', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.4.0/src/task_pool.rs:75:18
stack backtrace:
   0:     0x560211700280 - std::backtrace_rs::backtrace::libunwind::trace::h4e80f45db05e9df0
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x560211700280 - std::backtrace_rs::backtrace::trace_unsynchronized::h9db62a3d3587f6c3
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560211700280 - std::sys_common::backtrace::_print_fmt::h2fafbe52c9090591
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560211700280 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7d41ae04358c516d
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56021172305c - core::fmt::write::h968e6400cbc51d6a
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/core/src/fmt/mod.rs:1115:17
   5:     0x5602116fcf75 - std::io::Write::write_fmt::h2eaa97c6f8c9e829
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/io/mod.rs:1642:15
   6:     0x5602117022fb - std::sys_common::backtrace::_print::h601a6bc581f240d5
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5602117022fb - std::sys_common::backtrace::print::h8b96e15ba64b8e64
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5602117022fb - std::panicking::default_hook::{{closure}}::h94fa9d2f08c20620
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panicking.rs:208:50
   9:     0x560211701dd1 - std::panicking::default_hook::h6d463f5a2e9d9986
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panicking.rs:225:9
  10:     0x5602117029c4 - std::panicking::rust_panic_with_hook::h1e953652a338573e
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panicking.rs:622:17
  11:     0x5602117024a7 - std::panicking::begin_panic_handler::{{closure}}::h78bf2fec525c238a
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panicking.rs:519:13
  12:     0x56021170077c - std::sys_common::backtrace::__rust_end_short_backtrace::h651eb6282e4ea6b2
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x560211702409 - rust_begin_unwind
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panicking.rs:515:5
  14:     0x560210e275e1 - core::panicking::panic_fmt::hdfd0360cedf2d908
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/core/src/panicking.rs:92:14
  15:     0x560210e276d3 - core::result::unwrap_failed::hc9085c7b2fddd31a
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/core/src/result.rs:1355:5
  16:     0x5602116d4bbe - <bevy_tasks::task_pool::TaskPoolInner as core::ops::drop::Drop>::drop::h42cbf98450018c1a
  17:     0x560211615d58 - alloc::sync::Arc<T>::drop_slow::hc47d2d446c35417c
  18:     0x56021161aae3 - core::ptr::drop_in_place<bevy_ecs::resource::resources::VecResourceStorage<bevy_tasks::usages::IoTaskPool>>::h21095ed12002311c
  19:     0x5602111bb101 - core::ptr::drop_in_place<(core::any::TypeId,bevy_ecs::resource::resources::ResourceData)>::h9f9d5493521a9bee
  20:     0x5602111a3119 - core::ptr::drop_in_place<bevy_winit::winit_runner::{{closure}}>::h36710cebc0154a9e
  21:     0x5602111a4381 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h3884e264eb0eaed6
  22:     0x5602111a43bd - winit::platform_impl::platform::x11::EventLoop<T>::run::he51197aed15cf186
  23:     0x5602111c34dc - winit::platform_impl::platform::EventLoop<T>::run::h11b87b1ad1296bda
  24:     0x56021119c1ac - winit::event_loop::EventLoop<T>::run::h79399ceac2b975d4
  25:     0x56021119ff8c - bevy_winit::run::hf63ae5671a9f772f
  26:     0x5602111a00e3 - bevy_winit::winit_runner::h32d3507fbb43204f
  27:     0x5602111c2b14 - core::ops::function::Fn::call::h82af280453724466
  28:     0x5602116b7abf - bevy_app::app_builder::AppBuilder::run::he180d68fb59d3e31
  29:     0x560210e45da2 - colonize::main::h236025fca79e61ed
  30:     0x560210e72a03 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbb7f18409be4e6cb
  31:     0x560210e3e7b9 - std::rt::lang_start::{{closure}}::h579684c2289a8859
  32:     0x560211702eca - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hccffb0872f46e99d
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/core/src/ops/function.rs:259:13
  33:     0x560211702eca - std::panicking::try::do_call::h814e0410256bb9f2
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panicking.rs:401:40
  34:     0x560211702eca - std::panicking::try::h97cbec2057cc2c0d
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panicking.rs:365:19
  35:     0x560211702eca - std::panic::catch_unwind::h964f35f6fa41d1d7
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panic.rs:434:14
  36:     0x560211702eca - std::rt::lang_start_internal::{{closure}}::hb97931cf27086d8b
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/rt.rs:45:48
  37:     0x560211702eca - std::panicking::try::do_call::hf0d61be342e8297a
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panicking.rs:401:40
  38:     0x560211702eca - std::panicking::try::h6b40eeb22db57b23
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panicking.rs:365:19
  39:     0x560211702eca - std::panic::catch_unwind::h425af95fffdb0cf5
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/panic.rs:434:14
  40:     0x560211702eca - std::rt::lang_start_internal::h21e355575f2fedc7
                               at /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/library/std/src/rt.rs:45:20
  41:     0x560210e45e92 - main
  42:     0x7f59c4a9f09b - __libc_start_main
  43:     0x560210e2940a - _start
  44:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal Instruction
```

**Comment by ArthurHDRodrigues** [comment]
An additional info I fount out, the game works fine when I run `cargo run --release`, but crash as described above when I try to run `./target/release/colonize`...

**Comment by indiv0** [comment]
@ArthurHDRodrigues yeah looks like it can't find the path to the shader files when running. They need to be in the correct location relative to the executable, and they don't get copied over automatically right now.

If you copy the shader directory to the correct location (`colonize/assets/shaders` to `target/release/assets/shaders`) then it should work when running it with `./target/release/colonize`.
